In [1]:
#Matrix is representation of table of data

In [10]:
#np.reshape(*,*,'C') syntax to create matrix
#np.array()

In [7]:
import numpy as np

In [13]:
mydata=np.arange(0,20)

In [14]:
print mydata

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [20]:
np.reshape(mydata,(5,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [22]:
np.reshape(mydata,(5,4),order='C')   #Nothing Will change

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [23]:
MAT1=np.reshape(mydata,(5,4),order='C')
MAT1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [25]:
MAT1[2,2]   #(ROW,COLUMN)

10

In [29]:
MAT2=np.reshape(mydata,(5,4),order='F')   #F is flatten
MAT2

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [30]:
MAT2[0,2]

10

In [31]:
##OOP CONCEPT

In [33]:
mydata.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [34]:
#-----------

In [35]:
r1=["I","am","hAPPY"]
r2=["What","a","day"]
r3=[1,2,3]

In [36]:
[r1,r2,r3]

[['I', 'am', 'hAPPY'], ['What', 'a', 'day'], [1, 2, 3]]

In [37]:
np.array([r1,r2,r3])

array([['I', 'am', 'hAPPY'],
       ['What', 'a', 'day'],
       ['1', '2', '3']], dtype='|S5')

In [38]:
print np.array([r1,r2,r3])   

[['I' 'am' 'hAPPY']
 ['What' 'a' 'day']
 ['1' '2' '3']]


In [ ]:
#Here we can see that number (1,2,3) is chnaged in to string because array contains only type of data type